name: Cleanup Issues

on:
  workflow_dispatch:  # Manual trigger only

permissions:
  issues: write

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Delete All Issues
        env:
          GH_TOKEN: ${{ secrets.PAT_TOKEN }}
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.PAT_TOKEN }}
          script: |
            const { data: issues } = await github.rest.issues.listForRepo({
              owner: context.repo.owner,
              repo: context.repo.repo,
              state: 'all',
              per_page: 100
            });
            
            console.log(`Found ${issues.length} issues to delete`);
            
            for (const issue of issues) {
              if (!issue.pull_request) {  // Skip pull requests
                await github.rest.issues.update({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  issue_number: issue.number,
                  state: 'closed'
                });
                
                console.log(`Closed issue #${issue.number}: ${issue.title}`);
              }
            }
            
            console.log('All issues have been closed'); 