name: Project to TODO

on:
  workflow_dispatch:  # Manual trigger for testing
  schedule:
    - cron: '*/15 * * * *'  # Run every 15 minutes

permissions:
  contents: write
  issues: read
  repository-projects: read

jobs:
  update-todo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Update TODO.md from Project
        env:
          GH_TOKEN: ${{ secrets.PAT_TOKEN }}
          PROJECT_NUMBER: 2
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.PAT_TOKEN }}
          script: |
            const fs = require('fs');
            
            // Status mapping (reverse of the other workflow)
            const statusMap = {
              'BACKLOG': 'BACKLOG',
              'IN PROGRESS': 'IN PROGRESS',
              'TESTING': 'TESTING',
              'COMPLETE': 'COMPLETE'
            };
            
            try {
              // Get all project items
              const projectQuery = `
                query($owner: String!, $number: Int!) {
                  user(login: $owner) {
                    projectV2(number: $number) {
                      items(first: 100) {
                        nodes {
                          id
                          content {
                            ... on Issue {
                              title
                              state
                              number
                            }
                          }
                          fieldValues(first: 8) {
                            nodes {
                              ... on ProjectV2ItemFieldSingleSelectValue {
                                name
                              }
                            }
                          }
                        }
                      }
                    }
                  }
                }
              `;
              
              const projectResult = await github.graphql(projectQuery, {
                owner: context.repo.owner,
                number: parseInt(process.env.PROJECT_NUMBER)
              });
              
              // Organize items by status
              const sections = {
                'BACKLOG': [],
                'IN PROGRESS': [],
                'TESTING': [],
                'COMPLETE': []
              };
              
              // Process project items
              for (const item of projectResult.user.projectV2.items.nodes) {
                if (!item.content) continue; // Skip items that aren't issues
                
                const status = item.fieldValues.nodes.find(field => field.name)?.name || 'BACKLOG';
                const section = statusMap[status] || 'BACKLOG';
                
                sections[section].push({
                  title: item.content.title
                });
              }
              
              // Generate new TODO.md content
              let todoContent = '# Coffee Pub Crier - Tasks\n\n';
              
              for (const [section, tasks] of Object.entries(sections)) {
                if (tasks.length > 0) {
                  todoContent += `## ${section}\n`;
                  for (const task of tasks) {
                    todoContent += `- ${task.title}\n`;
                  }
                  todoContent += '\n';
                }
              }
              
              // Write the new content
              fs.writeFileSync('TODO.md', todoContent);
              
              // Create commit
              const { repo, owner } = context.repo;
              const currentBranch = 'master';
              
              // Get the current commit SHA
              const { data: ref } = await github.rest.git.getRef({
                owner,
                repo,
                ref: `heads/${currentBranch}`,
              });
              const currentSha = ref.object.sha;
              
              // Create blob with new content
              const { data: blob } = await github.rest.git.createBlob({
                owner,
                repo,
                content: todoContent,
                encoding: 'utf-8',
              });
              
              // Create tree
              const { data: tree } = await github.rest.git.createTree({
                owner,
                repo,
                base_tree: currentSha,
                tree: [{
                  path: 'TODO.md',
                  mode: '100644',
                  type: 'blob',
                  sha: blob.sha,
                }],
              });
              
              // Create commit
              const { data: commit } = await github.rest.git.createCommit({
                owner,
                repo,
                message: 'docs: sync TODO.md with project status',
                tree: tree.sha,
                parents: [currentSha],
              });
              
              // Update branch reference
              await github.rest.git.updateRef({
                owner,
                repo,
                ref: `heads/${currentBranch}`,
                sha: commit.sha,
              });
              
              console.log('Successfully updated TODO.md');
              
            } catch (error) {
              console.error('Error updating TODO.md:', error);
              console.error('Full error:', JSON.stringify(error, null, 2));
              process.exit(1);
            } 