name: Test Issue Query

on:
  workflow_dispatch:  # Manual trigger only

permissions:
  issues: read
  repository-projects: read

jobs:
  test-query:
    runs-on: ubuntu-latest
    steps:
      - name: Get All Issues
        env:
          GH_TOKEN: ${{ secrets.PAT_TOKEN }}
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.PAT_TOKEN }}
          script: |
            const query = `
              query($owner: String!, $repo: String!) {
                repository(owner: $owner, name: $repo) {
                  issues(first: 100, states: [OPEN, CLOSED]) {
                    nodes {
                      id
                      title
                      state
                      labels(first: 10) {
                        nodes {
                          name
                        }
                      }
                      projectItems(first: 10) {
                        nodes {
                          project {
                            title
                          }
                          fieldValues(first: 10) {
                            nodes {
                              ... on ProjectV2ItemFieldSingleSelectValue {
                                name
                                field {
                                  ... on ProjectV2SingleSelectField {
                                    name
                                  }
                                }
                              }
                            }
                          }
                        }
                      }
                    }
                  }
                }
              }
            `;
            
            const result = await github.graphql(query, {
              owner: context.repo.owner,
              repo: context.repo.repo
            });
            
            console.log('All Issues:', JSON.stringify(result, null, 2)); 