name: Test Issue Query

on:
  workflow_dispatch:  # Manual trigger only

permissions:
  issues: read
  repository-projects: read

jobs:
  test-query:
    runs-on: ubuntu-latest
    steps:
      - name: Test Project Query
        env:
          GH_TOKEN: ${{ secrets.PAT_TOKEN }}
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.PAT_TOKEN }}
          script: |
            const query = `
              query($owner: String!, $repo: String!) {
                repository(owner: $owner, name: $repo) {
                  projectV2(number: 2) {
                    title
                    items(first: 10) {
                      nodes {
                        id
                        fieldValues(first: 10) {
                          nodes {
                            ... on ProjectV2ItemFieldSingleSelectValue {
                              name
                              field {
                                ... on ProjectV2SingleSelectField {
                                  name
                                }
                              }
                            }
                            ... on ProjectV2ItemFieldDateValue {
                              date
                              field {
                                ... on ProjectV2Field {
                                  name
                                }
                              }
                            }
                            ... on ProjectV2ItemFieldTextValue {
                              text
                              field {
                                ... on ProjectV2Field {
                                  name
                                }
                              }
                            }
                          }
                        }
                        content {
                          ... on Issue {
                            title
                            number
                            state
                          }
                          ... on DraftIssue {
                            title
                          }
                        }
                      }
                    }
                  }
                }
              }
            `;
            
            const result = await github.graphql(query, {
              owner: context.repo.owner,
              repo: context.repo.repo
            });
            
            console.log('Query Result:', JSON.stringify(result, null, 2)); 